### ISSUE TITLE
Git diff background colours do not fit theme

### ISSUE THREAD

**Issue by n0v1** [vangware/dark-plus-material#12]
Dark+ Material 2.0.0 with VS code 1.31.1:

![image](https://user-images.githubusercontent.com/1246586/52703980-db69b200-2f7f-11e9-9159-373a36b1afd5.png)

In my opinion the red and green background colours do not really fit the rest of the theme. This was better in earlier versions. Those colours seem to match the ones from Dark+ (default dark).

I guess this was introduced with version 2.

To compare, here is Dark+ Material 1.4.8 with VS code 1.31.1:

![image](https://user-images.githubusercontent.com/1246586/52704341-9bef9580-2f80-11e9-8674-915cc2d8304a.png)

This might be a little too saturated. I guess something in between would be good.

**Comment by loucyx** [comment]
Hi @n0v1! Previously the code that takes the colors from the default "Dark+ Theme" didn't took into consideration the opacity values, so people made issues like this one: https://github.com/vangware/dark-plus-material/issues/6 ... the new code is able to handle opacity so that's why the changes look like this. Is more similar to the default, but still with material palette.
