### ISSUE TITLE
[Request] Port Theme to Visual Studio 2019+

### ISSUE THREAD

**Issue by johngagefaulkner** [vangware/dark-plus-material#23]
Please note this is only a "feature" request and not an issue.

Personally, I prefer using Visual Studio 2019 (Professional) to build applications using C# (because of the Designer) but I've gotten to the point where I design the UI in VS2019 then write the code using VS Code strictly because I like this theme that much. It'd be greatly appreciated if someone could port the theme to Visual Studio 2019 for people like me! 

Thank you.

**Comment by loucyx** [comment]
Hi @johngagefaulkner!

This theme is made by mapping theme colors from the default Dark+ theme of VS Code to the classic Material palette. A script takes one value and turns it into the other using that map.

In order to achieve what you requested we would have to have all the possible values of a Visual Studio theme, do the mappings all over and update the script to generate a theme file for that editor. All that is pretty out of scope, but you're more than welcome to fork and reuse whatever you find useful from this repo, which is MIT licensed.

If the fork will look the same I'll appreciate some credit, but other than that you can do whatever you want 😊
