### ISSUE TITLE
 Jupyter Notebook Cell Border Line

### ISSUE THREAD

**Issue by Tirbo06** [vangware/dark-plus-material#26]
Hi Vangware

I love your Dark+Material theme especially with Python, 
Since Vs Code Insider released a new version I have lost the "outline cells" of notebook jupyter (in vscode).

I am triying to find it in the "dark-plus-material.json"...
Do you have any hint to give me regarding wich line I could modify to make it wonderful again !?

Thanks you very much

![image](https://user-images.githubusercontent.com/59821431/127858439-146dd30d-657c-402b-a847-05dfe9bbaccc.png)

**Comment by loucyx** [comment]
I'll take a look and add a new response in this thread later if I find it, but **Dark+ Material** uses a script to turn the default **Dark+** colors that comes bundled with VSCode into Material colors, so being an automated process I don't actually know which property of all the properties is the one responsible for that border.

I'll close this but mainly because it seems is not an issue with the theme itself, but still once I figure it out I'll add a new comment in this thread!
