### ISSUE TITLE
Colors in v.3 are far less vivid than in v.2

### ISSUE THREAD

**Issue by SomwareHR** [vangware/dark-plus-material#27]
Don't know what's the reasoning behind changing the colors themes selected by - colors?
I mean, themes are specifically selected because of their, how to say.. colors and changing colors is not something that can improve experience of products selected exclusively thanks to their - colors :)

Anyway, switched back to v.2
Thanks!
BR

**Comment by loucyx** [comment]
The idea with Dark+ Material was always to be "Dark+ with the Material palette". Version 3 achieves this in a far better fashion using a LAB color difference algorithm (based on color perception). You can see this putting the original and Material next to each other:

![Similar](https://i.imgur.com/D3gucso.png)

And version 2:

![Not so similar](https://i.imgur.com/bFcXzq7.png)

As you mentioned, you can keep version 2, but you can also upgrade to v3 and just add this in your settings if you prefer a darker background, let's say you want it to be pure black:

```
"workbench.colorCustomizations": {
	"breadcrumb.background": "#000000",
	"editor.background": "#000000",
	"editorGutter.background": "#000000",
	"tab.activeBackground": "#000000"
},
```

The underlying code changes made in this theme also made possible to create new themes like the recently released [Dark + Tailwind](https://marketplace.visualstudio.com/items?itemName=vangware.dark-plus-tailwind) which uses [Tailwind's colors](https://tailwindcss.com/docs/customizing-colors), and with the previous approach this wasn't possible. This might not feel like it affects you as user of the themes directly, but maintenance and reuse are now far better than before, so I can release new versions faster and keep the colors concise because is now coming from an algorithm, not from manual fine tuning.

Cheers!

**Comment by akbyrd** [comment]
This is the second time this extension has randomly changed its color scheme. It's like drinking a root beer that suddenly decides it wants to be a pepsi. Very strong dislike.

**Comment by loucyx** [comment]
@akbyrd if you were here in v1, then you should be happy because v3 is closer to v1, and if you don't like it, you can keep v2, or customize v3 as explained in the previous comment. If you're very unhappy you can always pick other theme that makes you happier, or you could even fork this theme and create your own 😊

**Comment by irajeshh** [comment]
> The idea with Dark+ Material was always to be "Dark+ with the Material palette". Version 3 achieves this in a far better fashion using a LAB color difference algorithm (based on color perception). You can see this putting the original and Material next to each other:
> 
> ![Similar](https://camo.githubusercontent.com/369e2400530a71710efb0fdc95a2c9b3eee386cfd44e12ed4b402fdb10972d1d/68747470733a2f2f692e696d6775722e636f6d2f4433677563736f2e706e67)
> 
> And version 2:
> 
> ![Not so similar](https://camo.githubusercontent.com/2204fafd86e77c93c7fe22868ac39deb82d469af4bf96e4183b74444038740ff/68747470733a2f2f692e696d6775722e636f6d2f624663587a71372e706e67)
> 
> As you mentioned, you can keep version 2, but you can also upgrade to v3 and just add this in your settings if you prefer a darker background, let's say you want it to be pure black:
> 
> ```
> "workbench.colorCustomizations": {
> 	"breadcrumb.background": "#000000",
> 	"editor.background": "#000000",
> 	"editorGutter.background": "#000000",
> 	"tab.activeBackground": "#000000"
> },
> ```
> 
> The underlying code changes made in this theme also made possible to create new themes like the recently released [Dark + Tailwind](https://marketplace.visualstudio.com/items?itemName=vangware.dark-plus-tailwind) which uses [Tailwind's colors](https://tailwindcss.com/docs/customizing-colors), and with the previous approach this wasn't possible. This might not feel like it affects you as user of the themes directly, but maintenance and reuse are now far better than before, so I can release new versions faster and keep the colors concise because is now coming from an algorithm, not from manual fine tuning.
> 
> Cheers!

Today started with a bad moring!
This is okay for the background!, If possible, at least provide all color codes like this. I need the whole colors from version 2.0


Temporarily, I disabled `Check for extension updates` & `Auto update extensions` to `none.`
Then I installed [v 2.4.4 .vsix file.](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vangware/vsextensions/dark-plus-material/2.4.4/vspackage)
**This update is unfair.**

**Comment by loucyx** [comment]
@irajeshh If you want every single color of the previous version, you can simply use that version (it will not get upgraded automatically if you manually set the old version). You can do that by clicking on the :gear: icon that appears when you hover over the extension, it will show this menu:
![Screenshot of menu with "Install another version..." option selected](https://i.imgur.com/ijUrr9v.png)
Then click on "Install another version...", and select the last `v2.x` version:
![Screenshot of version select, with version 2.4.4 selected](https://i.imgur.com/v0cnkfk.png)
That will require a reload of VSCode, and once reloaded you should get the previous version. I'll locking this conversation so we avoid spamming poor @SomwareHR 

The update might be feel "unfair" to you, but trust me, is way more unfair to have to single handled maintain a theme getting just a few positive reviews, and every time I made a change that improves my experience for maintenance, I get all the "1/5" reviews. Folks are super vocal when they are unhappy, but say nothing when they are content with this, and completely forget there is another dev just like them doing the maintenance. That's OSS for you, I guess.
