### ISSUE TITLE
Colors seem wrong in version 3+

### ISSUE THREAD

**Issue by JoshuaBarnette** [vangware/dark-plus-material#29]
I have been using this theme for several years and starting with version 3.0.0 the background isn't black anymore. Now it is some grey color. Is this intentional, or is it something I'm doing wrong?

Version 2.4.4
![image](https://user-images.githubusercontent.com/29741586/148607016-98ca8678-78e7-4a49-8e63-6161a1326d83.png)

Version 3.0.3
![image](https://user-images.githubusercontent.com/29741586/148607075-d553ac82-6ab2-4294-93b9-8f183f7860d9.png)

**Comment by loucyx** [comment]
The change is intentional. It was explained in detail in [this comment](https://github.com/vangware/dark-plus-material/issues/27#issuecomment-1001706358), and a [new Customization section](https://github.com/vangware/dark-plus-material#customization) was added in the [README](https://github.com/vangware/dark-plus-material#readme) explaining how you can customize the theme if you want it to look darker. The TL;DR is that v3 is easier to maintain and closer to the default Dark+ theme, while still using Material's palette. If you prefer a darker background, the [Tailwind variant of the theme](https://lshi.ru/dark-plus-tailwind) is a little bit darker.
