### ISSUE TITLE
Changet text color in HTML

### ISSUE THREAD

**Issue by Linxflasher** [vangware/dark-plus-material#5]
Hello!

Really love your theme. One thing I want to change is the text color in HTML (want to make it white or close to it). Could you please tell me where i can change it?

**Comment by loucyx** [comment]
Hi @Linxflasher! Sorry for the late reply. If you want to change some color you can add the property `workbench.colorCustomizations` in your settings, and look for the property that match your requirements. I don't know wich property is the one that sets the color of the HTML, because this theme is updated automatically with a color map and the latest version of the default Dark+ theme (that's why is always up-to-date).

Reference: https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme

**Comment by Linxflasher** [comment]
I see. Thanks for your reply!
